### ISSUE TITLE
Group-buying

### ISSUE THREAD

**Issue by hoosin** [hoosin/Group-buying#1]
```md
## hoosin

- Posters - 24"x36" / Launch
- Sticker Packs - Sticker Pack Four 
- Atom And Electron Sticker Pack - Atom and Electron Sticker Pack 
- Arctocat - Linear / Men's Large

### total 55
```

**Comment by hoosin** [comment]
## hoosin

- Posters - 24"x36" / Launch
- Atom And Electron Sticker Pack - Atom and Electron Sticker Pack 

### total 30

**Comment by salcabar** [comment]
## salcabar

- Sticker Packs - Sticker Pack Four 
- Octicon Sticker Packs - Code 
- Atom And Electron Sticker Pack - Atom and Electron Sticker Pack 
- Cork Coasters - Cork Coasters 
- Octocat Mug - White 

### total 34

**Comment by x-yao** [comment]
## xyao

- Sticker Packs - Sticker Pack 1-5
- Octocat Figurine - 5"

### total 55

**Comment by aiyoufu** [comment]
## aigo

* 之前的取消，暂时不拼了，抱歉各位大大
### total 0

**Comment by renfufei** [comment]
## renfufei

- Sticker Packs - Sticker Pack Two
- Octocat Figurine - `3"` Octocat Figurine

### total 20

**Comment by idododu** [comment]
## dodo

- Activity Book
- Octocat Figurine - 3"
- Black GitHub Mug
- Sticker Packs - Sticker Pack Five 

### total $39

**Comment by Yuanbin-xavier** [comment]
## Xavier

- Octopolo Shirt - Linear / Men's XL

### total $30

**Comment by hoosin** [comment]
![image](https://cloud.githubusercontent.com/assets/3365399/23289292/a4973992-fa83-11e6-8b6a-347f93030fdf.png)


![image](https://cloud.githubusercontent.com/assets/3365399/23289971/6a5a2dde-fa88-11e6-9683-6372fba75625.png)


```javascript
  
    var express = 47.39 / 6
    var exchange = 6.8703

    var hoosin = (30 + express) * exchange // 260.3729195
    var salcabar = (34 + express) * exchange  // 287.8541195
    var xyao = (55 + express) * exchange  // 432.1304195
    var renfufei = (20 + express) * exchange  //191.66991950000002
    var dodo = (39 + express) * exchange  // 322.2056195
    var Xavier = (30 + express) * exchange  // 260.3729195

```
