### ISSUE TITLE
Group-buying-2018-Summer

### ISSUE THREAD

**Issue by hoosin** [hoosin/Group-buying#2]
本次活动为非盈利性质的组团搭车，自愿上车，自愿下车。

- GitHub Shop 支持直邮，直邮中国邮费在 $20 至 $30 两个档次，人越多邮费就越便宜；而且人多东西多发的都是大箱子，快递小哥得多暴力多想不开才能疯狂扔一个大箱子，如果有易碎品那物品安全比起小包就很有保障

- 不支持退货，运输风险自担，多退少补，公开透明，坦白从宽，抗拒从严

- GitHub Shop 中的商品不限品类不限数量，但是数量、种类和是否需要 DIY 一定要明确

- 根据过往经验，有可能会被税的风险，产生的税可能需要大家平摊

**有需求的小伙伴可以按照以下格式跟 issues**

```md
## hoosin

- Posters - 24"x36" / Launch
- Sticker Packs - Sticker Pack Four 
- Atom And Electron Sticker Pack - Atom and Electron Sticker Pack 
- Arctocat - Linear / Men's Large

### total 55
```

**Comment by smallke** [comment]
## 小可

- Sticker Packs -  Sticker Pack Three
- I [octocat] Code 2.0 Shirt -Linear/Men’s -  Large

### total 30

**Comment by hoosin** [comment]
https://cnodejs.org/topic/583c5d9fba57ffba06c24a89
